//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Bookingdetails = new HashSet<Bookingdetail>();
        }
    
        public int RoomId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<int> RoomNo { get; set; }
        public string RoomType { get; set; }
        public Nullable<int> RoomCost { get; set; }
        public string BookingStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookingdetail> Bookingdetails { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
